#!/bin/sh
# SPDX-License-Identifier: GPL-2.0

ATOMICDIR=$(dirname $0)

. ${ATOMICDIR}/atomic-tbl.sh

#gen_proto_order_variant(meta, pfx, name, sfx, order, atomic, arg...)
gen_proto_order_variant()
{
	local meta="$1"; shift
	local pfx="$1"; shift
	local name="$1"; shift
	local sfx="$1"; shift
	local order="$1"; shift
	local atomic="$1"; shift

	local atomicname="${atomic}_${pfx}${name}${sfx}${order}"

	printf "\t__do(${atomicname}) \\"
	printf "\n"
}

cat << EOF
// SPDX-License-Identifier: GPL-2.0

// Generated by $0
// DO NOT MODIFY THIS FILE DIRECTLY

#ifndef _LINUX_ATOMIC_STATS_H
#define _LINUX_ATOMIC_STATS_H

#if defined(CONFIG_ATOMIC_STATS) && !defined(DISABLE_ATOMIC_STATS)
/*
 * This macro will use __do() on each atomic_*() operation in turn.
 * This can be used to generate enums and enum-to-string tables.
 */
#define __do_atomic_stats_ops(__do)	\\
EOF

grep '^[a-z]' "$1" | while read name meta args; do
	gen_proto "${meta}" "${name}" "atomic" ${args}
done

grep '^[a-z]' "$1" | while read name meta args; do
	gen_proto "${meta}" "${name}" "atomic64" ${args}
done

grep '^[a-z]' "$1" | while read name meta args; do
	gen_proto "${meta}" "${name}" "atomic_long" ${args}
done

cat <<EOF
	/* consume trailing newline escape */

#define __do_atomic_stats_enum(x)	ATOMIC_STATS_##x,

enum atomic_stats_op {
	__do_atomic_stats_ops(__do_atomic_stats_enum)
	NR_ATOMIC_STATS_OPS
};

void __atomic_stats_inc(enum atomic_stats_op op);
#define atomic_stats_inc(op) \\
	__atomic_stats_inc(ATOMIC_STATS_##op);

void __atomic_stats_bool_inc(enum atomic_stats_op op, bool ret);
#define atomic_stats_bool_inc(op, ret) \\
	__atomic_stats_bool_inc(ATOMIC_STATS_##op, ret);

#else
#define atomic_stats_inc(op)
#define atomic_stats_bool_inc(op, ret)
#endif

#endif /* _LINUX_ATOMIC_STATS_H */
EOF
