// SPDX-License-Identifier: GPL-2.0

// Generated by scripts/atomic/gen-atomic-outlined.sh
// DO NOT MODIFY THIS FILE DIRECTLY

/*
 * This file provides out-of-line wrappers for the various atomic functions.
 */
#ifndef _LINUX_ATOMIC_OUTLINED_H
#define _LINUX_ATOMIC_OUTLINED_H

#include <linux/atomic.h>

noinline noinstr int
outlined_raw_atomic_read(const atomic_t *v)
{
	return raw_atomic_read(v);
}

noinline noinstr int
outlined_raw_atomic_read_acquire(const atomic_t *v)
{
	return raw_atomic_read_acquire(v);
}

noinline int
outlined_atomic_read(const atomic_t *v)
{
	return atomic_read(v);
}

noinline int
outlined_atomic_read_acquire(const atomic_t *v)
{
	return atomic_read_acquire(v);
}

noinline noinstr void
outlined_raw_atomic_set(atomic_t *v, int i)
{
	raw_atomic_set(v, i);
}

noinline noinstr void
outlined_raw_atomic_set_release(atomic_t *v, int i)
{
	raw_atomic_set_release(v, i);
}

noinline void
outlined_atomic_set(atomic_t *v, int i)
{
	atomic_set(v, i);
}

noinline void
outlined_atomic_set_release(atomic_t *v, int i)
{
	atomic_set_release(v, i);
}

noinline noinstr void
outlined_raw_atomic_add(int i, atomic_t *v)
{
	raw_atomic_add(i, v);
}

noinline noinstr int
outlined_raw_atomic_add_return(int i, atomic_t *v)
{
	return raw_atomic_add_return(i, v);
}

noinline noinstr int
outlined_raw_atomic_add_return_acquire(int i, atomic_t *v)
{
	return raw_atomic_add_return_acquire(i, v);
}

noinline noinstr int
outlined_raw_atomic_add_return_release(int i, atomic_t *v)
{
	return raw_atomic_add_return_release(i, v);
}

noinline noinstr int
outlined_raw_atomic_add_return_relaxed(int i, atomic_t *v)
{
	return raw_atomic_add_return_relaxed(i, v);
}

noinline noinstr int
outlined_raw_atomic_fetch_add(int i, atomic_t *v)
{
	return raw_atomic_fetch_add(i, v);
}

noinline noinstr int
outlined_raw_atomic_fetch_add_acquire(int i, atomic_t *v)
{
	return raw_atomic_fetch_add_acquire(i, v);
}

noinline noinstr int
outlined_raw_atomic_fetch_add_release(int i, atomic_t *v)
{
	return raw_atomic_fetch_add_release(i, v);
}

noinline noinstr int
outlined_raw_atomic_fetch_add_relaxed(int i, atomic_t *v)
{
	return raw_atomic_fetch_add_relaxed(i, v);
}

noinline void
outlined_atomic_add(int i, atomic_t *v)
{
	atomic_add(i, v);
}

noinline int
outlined_atomic_add_return(int i, atomic_t *v)
{
	return atomic_add_return(i, v);
}

noinline int
outlined_atomic_add_return_acquire(int i, atomic_t *v)
{
	return atomic_add_return_acquire(i, v);
}

noinline int
outlined_atomic_add_return_release(int i, atomic_t *v)
{
	return atomic_add_return_release(i, v);
}

noinline int
outlined_atomic_add_return_relaxed(int i, atomic_t *v)
{
	return atomic_add_return_relaxed(i, v);
}

noinline int
outlined_atomic_fetch_add(int i, atomic_t *v)
{
	return atomic_fetch_add(i, v);
}

noinline int
outlined_atomic_fetch_add_acquire(int i, atomic_t *v)
{
	return atomic_fetch_add_acquire(i, v);
}

noinline int
outlined_atomic_fetch_add_release(int i, atomic_t *v)
{
	return atomic_fetch_add_release(i, v);
}

noinline int
outlined_atomic_fetch_add_relaxed(int i, atomic_t *v)
{
	return atomic_fetch_add_relaxed(i, v);
}

noinline noinstr void
outlined_raw_atomic_sub(int i, atomic_t *v)
{
	raw_atomic_sub(i, v);
}

noinline noinstr int
outlined_raw_atomic_sub_return(int i, atomic_t *v)
{
	return raw_atomic_sub_return(i, v);
}

noinline noinstr int
outlined_raw_atomic_sub_return_acquire(int i, atomic_t *v)
{
	return raw_atomic_sub_return_acquire(i, v);
}

noinline noinstr int
outlined_raw_atomic_sub_return_release(int i, atomic_t *v)
{
	return raw_atomic_sub_return_release(i, v);
}

noinline noinstr int
outlined_raw_atomic_sub_return_relaxed(int i, atomic_t *v)
{
	return raw_atomic_sub_return_relaxed(i, v);
}

noinline noinstr int
outlined_raw_atomic_fetch_sub(int i, atomic_t *v)
{
	return raw_atomic_fetch_sub(i, v);
}

noinline noinstr int
outlined_raw_atomic_fetch_sub_acquire(int i, atomic_t *v)
{
	return raw_atomic_fetch_sub_acquire(i, v);
}

noinline noinstr int
outlined_raw_atomic_fetch_sub_release(int i, atomic_t *v)
{
	return raw_atomic_fetch_sub_release(i, v);
}

noinline noinstr int
outlined_raw_atomic_fetch_sub_relaxed(int i, atomic_t *v)
{
	return raw_atomic_fetch_sub_relaxed(i, v);
}

noinline void
outlined_atomic_sub(int i, atomic_t *v)
{
	atomic_sub(i, v);
}

noinline int
outlined_atomic_sub_return(int i, atomic_t *v)
{
	return atomic_sub_return(i, v);
}

noinline int
outlined_atomic_sub_return_acquire(int i, atomic_t *v)
{
	return atomic_sub_return_acquire(i, v);
}

noinline int
outlined_atomic_sub_return_release(int i, atomic_t *v)
{
	return atomic_sub_return_release(i, v);
}

noinline int
outlined_atomic_sub_return_relaxed(int i, atomic_t *v)
{
	return atomic_sub_return_relaxed(i, v);
}

noinline int
outlined_atomic_fetch_sub(int i, atomic_t *v)
{
	return atomic_fetch_sub(i, v);
}

noinline int
outlined_atomic_fetch_sub_acquire(int i, atomic_t *v)
{
	return atomic_fetch_sub_acquire(i, v);
}

noinline int
outlined_atomic_fetch_sub_release(int i, atomic_t *v)
{
	return atomic_fetch_sub_release(i, v);
}

noinline int
outlined_atomic_fetch_sub_relaxed(int i, atomic_t *v)
{
	return atomic_fetch_sub_relaxed(i, v);
}

noinline noinstr void
outlined_raw_atomic_inc(atomic_t *v)
{
	raw_atomic_inc(v);
}

noinline noinstr int
outlined_raw_atomic_inc_return(atomic_t *v)
{
	return raw_atomic_inc_return(v);
}

noinline noinstr int
outlined_raw_atomic_inc_return_acquire(atomic_t *v)
{
	return raw_atomic_inc_return_acquire(v);
}

noinline noinstr int
outlined_raw_atomic_inc_return_release(atomic_t *v)
{
	return raw_atomic_inc_return_release(v);
}

noinline noinstr int
outlined_raw_atomic_inc_return_relaxed(atomic_t *v)
{
	return raw_atomic_inc_return_relaxed(v);
}

noinline noinstr int
outlined_raw_atomic_fetch_inc(atomic_t *v)
{
	return raw_atomic_fetch_inc(v);
}

noinline noinstr int
outlined_raw_atomic_fetch_inc_acquire(atomic_t *v)
{
	return raw_atomic_fetch_inc_acquire(v);
}

noinline noinstr int
outlined_raw_atomic_fetch_inc_release(atomic_t *v)
{
	return raw_atomic_fetch_inc_release(v);
}

noinline noinstr int
outlined_raw_atomic_fetch_inc_relaxed(atomic_t *v)
{
	return raw_atomic_fetch_inc_relaxed(v);
}

noinline void
outlined_atomic_inc(atomic_t *v)
{
	atomic_inc(v);
}

noinline int
outlined_atomic_inc_return(atomic_t *v)
{
	return atomic_inc_return(v);
}

noinline int
outlined_atomic_inc_return_acquire(atomic_t *v)
{
	return atomic_inc_return_acquire(v);
}

noinline int
outlined_atomic_inc_return_release(atomic_t *v)
{
	return atomic_inc_return_release(v);
}

noinline int
outlined_atomic_inc_return_relaxed(atomic_t *v)
{
	return atomic_inc_return_relaxed(v);
}

noinline int
outlined_atomic_fetch_inc(atomic_t *v)
{
	return atomic_fetch_inc(v);
}

noinline int
outlined_atomic_fetch_inc_acquire(atomic_t *v)
{
	return atomic_fetch_inc_acquire(v);
}

noinline int
outlined_atomic_fetch_inc_release(atomic_t *v)
{
	return atomic_fetch_inc_release(v);
}

noinline int
outlined_atomic_fetch_inc_relaxed(atomic_t *v)
{
	return atomic_fetch_inc_relaxed(v);
}

noinline noinstr void
outlined_raw_atomic_dec(atomic_t *v)
{
	raw_atomic_dec(v);
}

noinline noinstr int
outlined_raw_atomic_dec_return(atomic_t *v)
{
	return raw_atomic_dec_return(v);
}

noinline noinstr int
outlined_raw_atomic_dec_return_acquire(atomic_t *v)
{
	return raw_atomic_dec_return_acquire(v);
}

noinline noinstr int
outlined_raw_atomic_dec_return_release(atomic_t *v)
{
	return raw_atomic_dec_return_release(v);
}

noinline noinstr int
outlined_raw_atomic_dec_return_relaxed(atomic_t *v)
{
	return raw_atomic_dec_return_relaxed(v);
}

noinline noinstr int
outlined_raw_atomic_fetch_dec(atomic_t *v)
{
	return raw_atomic_fetch_dec(v);
}

noinline noinstr int
outlined_raw_atomic_fetch_dec_acquire(atomic_t *v)
{
	return raw_atomic_fetch_dec_acquire(v);
}

noinline noinstr int
outlined_raw_atomic_fetch_dec_release(atomic_t *v)
{
	return raw_atomic_fetch_dec_release(v);
}

noinline noinstr int
outlined_raw_atomic_fetch_dec_relaxed(atomic_t *v)
{
	return raw_atomic_fetch_dec_relaxed(v);
}

noinline void
outlined_atomic_dec(atomic_t *v)
{
	atomic_dec(v);
}

noinline int
outlined_atomic_dec_return(atomic_t *v)
{
	return atomic_dec_return(v);
}

noinline int
outlined_atomic_dec_return_acquire(atomic_t *v)
{
	return atomic_dec_return_acquire(v);
}

noinline int
outlined_atomic_dec_return_release(atomic_t *v)
{
	return atomic_dec_return_release(v);
}

noinline int
outlined_atomic_dec_return_relaxed(atomic_t *v)
{
	return atomic_dec_return_relaxed(v);
}

noinline int
outlined_atomic_fetch_dec(atomic_t *v)
{
	return atomic_fetch_dec(v);
}

noinline int
outlined_atomic_fetch_dec_acquire(atomic_t *v)
{
	return atomic_fetch_dec_acquire(v);
}

noinline int
outlined_atomic_fetch_dec_release(atomic_t *v)
{
	return atomic_fetch_dec_release(v);
}

noinline int
outlined_atomic_fetch_dec_relaxed(atomic_t *v)
{
	return atomic_fetch_dec_relaxed(v);
}

noinline noinstr void
outlined_raw_atomic_and(int i, atomic_t *v)
{
	raw_atomic_and(i, v);
}

noinline noinstr int
outlined_raw_atomic_fetch_and(int i, atomic_t *v)
{
	return raw_atomic_fetch_and(i, v);
}

noinline noinstr int
outlined_raw_atomic_fetch_and_acquire(int i, atomic_t *v)
{
	return raw_atomic_fetch_and_acquire(i, v);
}

noinline noinstr int
outlined_raw_atomic_fetch_and_release(int i, atomic_t *v)
{
	return raw_atomic_fetch_and_release(i, v);
}

noinline noinstr int
outlined_raw_atomic_fetch_and_relaxed(int i, atomic_t *v)
{
	return raw_atomic_fetch_and_relaxed(i, v);
}

noinline void
outlined_atomic_and(int i, atomic_t *v)
{
	atomic_and(i, v);
}

noinline int
outlined_atomic_fetch_and(int i, atomic_t *v)
{
	return atomic_fetch_and(i, v);
}

noinline int
outlined_atomic_fetch_and_acquire(int i, atomic_t *v)
{
	return atomic_fetch_and_acquire(i, v);
}

noinline int
outlined_atomic_fetch_and_release(int i, atomic_t *v)
{
	return atomic_fetch_and_release(i, v);
}

noinline int
outlined_atomic_fetch_and_relaxed(int i, atomic_t *v)
{
	return atomic_fetch_and_relaxed(i, v);
}

noinline noinstr void
outlined_raw_atomic_andnot(int i, atomic_t *v)
{
	raw_atomic_andnot(i, v);
}

noinline noinstr int
outlined_raw_atomic_fetch_andnot(int i, atomic_t *v)
{
	return raw_atomic_fetch_andnot(i, v);
}

noinline noinstr int
outlined_raw_atomic_fetch_andnot_acquire(int i, atomic_t *v)
{
	return raw_atomic_fetch_andnot_acquire(i, v);
}

noinline noinstr int
outlined_raw_atomic_fetch_andnot_release(int i, atomic_t *v)
{
	return raw_atomic_fetch_andnot_release(i, v);
}

noinline noinstr int
outlined_raw_atomic_fetch_andnot_relaxed(int i, atomic_t *v)
{
	return raw_atomic_fetch_andnot_relaxed(i, v);
}

noinline void
outlined_atomic_andnot(int i, atomic_t *v)
{
	atomic_andnot(i, v);
}

noinline int
outlined_atomic_fetch_andnot(int i, atomic_t *v)
{
	return atomic_fetch_andnot(i, v);
}

noinline int
outlined_atomic_fetch_andnot_acquire(int i, atomic_t *v)
{
	return atomic_fetch_andnot_acquire(i, v);
}

noinline int
outlined_atomic_fetch_andnot_release(int i, atomic_t *v)
{
	return atomic_fetch_andnot_release(i, v);
}

noinline int
outlined_atomic_fetch_andnot_relaxed(int i, atomic_t *v)
{
	return atomic_fetch_andnot_relaxed(i, v);
}

noinline noinstr void
outlined_raw_atomic_or(int i, atomic_t *v)
{
	raw_atomic_or(i, v);
}

noinline noinstr int
outlined_raw_atomic_fetch_or(int i, atomic_t *v)
{
	return raw_atomic_fetch_or(i, v);
}

noinline noinstr int
outlined_raw_atomic_fetch_or_acquire(int i, atomic_t *v)
{
	return raw_atomic_fetch_or_acquire(i, v);
}

noinline noinstr int
outlined_raw_atomic_fetch_or_release(int i, atomic_t *v)
{
	return raw_atomic_fetch_or_release(i, v);
}

noinline noinstr int
outlined_raw_atomic_fetch_or_relaxed(int i, atomic_t *v)
{
	return raw_atomic_fetch_or_relaxed(i, v);
}

noinline void
outlined_atomic_or(int i, atomic_t *v)
{
	atomic_or(i, v);
}

noinline int
outlined_atomic_fetch_or(int i, atomic_t *v)
{
	return atomic_fetch_or(i, v);
}

noinline int
outlined_atomic_fetch_or_acquire(int i, atomic_t *v)
{
	return atomic_fetch_or_acquire(i, v);
}

noinline int
outlined_atomic_fetch_or_release(int i, atomic_t *v)
{
	return atomic_fetch_or_release(i, v);
}

noinline int
outlined_atomic_fetch_or_relaxed(int i, atomic_t *v)
{
	return atomic_fetch_or_relaxed(i, v);
}

noinline noinstr void
outlined_raw_atomic_xor(int i, atomic_t *v)
{
	raw_atomic_xor(i, v);
}

noinline noinstr int
outlined_raw_atomic_fetch_xor(int i, atomic_t *v)
{
	return raw_atomic_fetch_xor(i, v);
}

noinline noinstr int
outlined_raw_atomic_fetch_xor_acquire(int i, atomic_t *v)
{
	return raw_atomic_fetch_xor_acquire(i, v);
}

noinline noinstr int
outlined_raw_atomic_fetch_xor_release(int i, atomic_t *v)
{
	return raw_atomic_fetch_xor_release(i, v);
}

noinline noinstr int
outlined_raw_atomic_fetch_xor_relaxed(int i, atomic_t *v)
{
	return raw_atomic_fetch_xor_relaxed(i, v);
}

noinline void
outlined_atomic_xor(int i, atomic_t *v)
{
	atomic_xor(i, v);
}

noinline int
outlined_atomic_fetch_xor(int i, atomic_t *v)
{
	return atomic_fetch_xor(i, v);
}

noinline int
outlined_atomic_fetch_xor_acquire(int i, atomic_t *v)
{
	return atomic_fetch_xor_acquire(i, v);
}

noinline int
outlined_atomic_fetch_xor_release(int i, atomic_t *v)
{
	return atomic_fetch_xor_release(i, v);
}

noinline int
outlined_atomic_fetch_xor_relaxed(int i, atomic_t *v)
{
	return atomic_fetch_xor_relaxed(i, v);
}

noinline noinstr int
outlined_raw_atomic_xchg(atomic_t *v, int new)
{
	return raw_atomic_xchg(v, new);
}

noinline noinstr int
outlined_raw_atomic_xchg_acquire(atomic_t *v, int new)
{
	return raw_atomic_xchg_acquire(v, new);
}

noinline noinstr int
outlined_raw_atomic_xchg_release(atomic_t *v, int new)
{
	return raw_atomic_xchg_release(v, new);
}

noinline noinstr int
outlined_raw_atomic_xchg_relaxed(atomic_t *v, int new)
{
	return raw_atomic_xchg_relaxed(v, new);
}

noinline int
outlined_atomic_xchg(atomic_t *v, int new)
{
	return atomic_xchg(v, new);
}

noinline int
outlined_atomic_xchg_acquire(atomic_t *v, int new)
{
	return atomic_xchg_acquire(v, new);
}

noinline int
outlined_atomic_xchg_release(atomic_t *v, int new)
{
	return atomic_xchg_release(v, new);
}

noinline int
outlined_atomic_xchg_relaxed(atomic_t *v, int new)
{
	return atomic_xchg_relaxed(v, new);
}

noinline noinstr int
outlined_raw_atomic_cmpxchg(atomic_t *v, int old, int new)
{
	return raw_atomic_cmpxchg(v, old, new);
}

noinline noinstr int
outlined_raw_atomic_cmpxchg_acquire(atomic_t *v, int old, int new)
{
	return raw_atomic_cmpxchg_acquire(v, old, new);
}

noinline noinstr int
outlined_raw_atomic_cmpxchg_release(atomic_t *v, int old, int new)
{
	return raw_atomic_cmpxchg_release(v, old, new);
}

noinline noinstr int
outlined_raw_atomic_cmpxchg_relaxed(atomic_t *v, int old, int new)
{
	return raw_atomic_cmpxchg_relaxed(v, old, new);
}

noinline int
outlined_atomic_cmpxchg(atomic_t *v, int old, int new)
{
	return atomic_cmpxchg(v, old, new);
}

noinline int
outlined_atomic_cmpxchg_acquire(atomic_t *v, int old, int new)
{
	return atomic_cmpxchg_acquire(v, old, new);
}

noinline int
outlined_atomic_cmpxchg_release(atomic_t *v, int old, int new)
{
	return atomic_cmpxchg_release(v, old, new);
}

noinline int
outlined_atomic_cmpxchg_relaxed(atomic_t *v, int old, int new)
{
	return atomic_cmpxchg_relaxed(v, old, new);
}

noinline noinstr bool
outlined_raw_atomic_try_cmpxchg(atomic_t *v, int *old, int new)
{
	return raw_atomic_try_cmpxchg(v, old, new);
}

noinline noinstr bool
outlined_raw_atomic_try_cmpxchg_acquire(atomic_t *v, int *old, int new)
{
	return raw_atomic_try_cmpxchg_acquire(v, old, new);
}

noinline noinstr bool
outlined_raw_atomic_try_cmpxchg_release(atomic_t *v, int *old, int new)
{
	return raw_atomic_try_cmpxchg_release(v, old, new);
}

noinline noinstr bool
outlined_raw_atomic_try_cmpxchg_relaxed(atomic_t *v, int *old, int new)
{
	return raw_atomic_try_cmpxchg_relaxed(v, old, new);
}

noinline bool
outlined_atomic_try_cmpxchg(atomic_t *v, int *old, int new)
{
	return atomic_try_cmpxchg(v, old, new);
}

noinline bool
outlined_atomic_try_cmpxchg_acquire(atomic_t *v, int *old, int new)
{
	return atomic_try_cmpxchg_acquire(v, old, new);
}

noinline bool
outlined_atomic_try_cmpxchg_release(atomic_t *v, int *old, int new)
{
	return atomic_try_cmpxchg_release(v, old, new);
}

noinline bool
outlined_atomic_try_cmpxchg_relaxed(atomic_t *v, int *old, int new)
{
	return atomic_try_cmpxchg_relaxed(v, old, new);
}

noinline noinstr bool
outlined_raw_atomic_sub_and_test(int i, atomic_t *v)
{
	return raw_atomic_sub_and_test(i, v);
}

noinline bool
outlined_atomic_sub_and_test(int i, atomic_t *v)
{
	return atomic_sub_and_test(i, v);
}

noinline noinstr bool
outlined_raw_atomic_dec_and_test(atomic_t *v)
{
	return raw_atomic_dec_and_test(v);
}

noinline bool
outlined_atomic_dec_and_test(atomic_t *v)
{
	return atomic_dec_and_test(v);
}

noinline noinstr bool
outlined_raw_atomic_inc_and_test(atomic_t *v)
{
	return raw_atomic_inc_and_test(v);
}

noinline bool
outlined_atomic_inc_and_test(atomic_t *v)
{
	return atomic_inc_and_test(v);
}

noinline noinstr bool
outlined_raw_atomic_add_negative(int i, atomic_t *v)
{
	return raw_atomic_add_negative(i, v);
}

noinline noinstr bool
outlined_raw_atomic_add_negative_acquire(int i, atomic_t *v)
{
	return raw_atomic_add_negative_acquire(i, v);
}

noinline noinstr bool
outlined_raw_atomic_add_negative_release(int i, atomic_t *v)
{
	return raw_atomic_add_negative_release(i, v);
}

noinline noinstr bool
outlined_raw_atomic_add_negative_relaxed(int i, atomic_t *v)
{
	return raw_atomic_add_negative_relaxed(i, v);
}

noinline bool
outlined_atomic_add_negative(int i, atomic_t *v)
{
	return atomic_add_negative(i, v);
}

noinline bool
outlined_atomic_add_negative_acquire(int i, atomic_t *v)
{
	return atomic_add_negative_acquire(i, v);
}

noinline bool
outlined_atomic_add_negative_release(int i, atomic_t *v)
{
	return atomic_add_negative_release(i, v);
}

noinline bool
outlined_atomic_add_negative_relaxed(int i, atomic_t *v)
{
	return atomic_add_negative_relaxed(i, v);
}

noinline noinstr int
outlined_raw_atomic_fetch_add_unless(atomic_t *v, int a, int u)
{
	return raw_atomic_fetch_add_unless(v, a, u);
}

noinline noinstr bool
outlined_raw_atomic_add_unless(atomic_t *v, int a, int u)
{
	return raw_atomic_add_unless(v, a, u);
}

noinline int
outlined_atomic_fetch_add_unless(atomic_t *v, int a, int u)
{
	return atomic_fetch_add_unless(v, a, u);
}

noinline bool
outlined_atomic_add_unless(atomic_t *v, int a, int u)
{
	return atomic_add_unless(v, a, u);
}

noinline noinstr bool
outlined_raw_atomic_inc_not_zero(atomic_t *v)
{
	return raw_atomic_inc_not_zero(v);
}

noinline bool
outlined_atomic_inc_not_zero(atomic_t *v)
{
	return atomic_inc_not_zero(v);
}

noinline noinstr bool
outlined_raw_atomic_inc_unless_negative(atomic_t *v)
{
	return raw_atomic_inc_unless_negative(v);
}

noinline bool
outlined_atomic_inc_unless_negative(atomic_t *v)
{
	return atomic_inc_unless_negative(v);
}

noinline noinstr bool
outlined_raw_atomic_dec_unless_positive(atomic_t *v)
{
	return raw_atomic_dec_unless_positive(v);
}

noinline bool
outlined_atomic_dec_unless_positive(atomic_t *v)
{
	return atomic_dec_unless_positive(v);
}

noinline noinstr int
outlined_raw_atomic_dec_if_positive(atomic_t *v)
{
	return raw_atomic_dec_if_positive(v);
}

noinline int
outlined_atomic_dec_if_positive(atomic_t *v)
{
	return atomic_dec_if_positive(v);
}

noinline noinstr s64
outlined_raw_atomic64_read(const atomic64_t *v)
{
	return raw_atomic64_read(v);
}

noinline noinstr s64
outlined_raw_atomic64_read_acquire(const atomic64_t *v)
{
	return raw_atomic64_read_acquire(v);
}

noinline s64
outlined_atomic64_read(const atomic64_t *v)
{
	return atomic64_read(v);
}

noinline s64
outlined_atomic64_read_acquire(const atomic64_t *v)
{
	return atomic64_read_acquire(v);
}

noinline noinstr void
outlined_raw_atomic64_set(atomic64_t *v, s64 i)
{
	raw_atomic64_set(v, i);
}

noinline noinstr void
outlined_raw_atomic64_set_release(atomic64_t *v, s64 i)
{
	raw_atomic64_set_release(v, i);
}

noinline void
outlined_atomic64_set(atomic64_t *v, s64 i)
{
	atomic64_set(v, i);
}

noinline void
outlined_atomic64_set_release(atomic64_t *v, s64 i)
{
	atomic64_set_release(v, i);
}

noinline noinstr void
outlined_raw_atomic64_add(s64 i, atomic64_t *v)
{
	raw_atomic64_add(i, v);
}

noinline noinstr s64
outlined_raw_atomic64_add_return(s64 i, atomic64_t *v)
{
	return raw_atomic64_add_return(i, v);
}

noinline noinstr s64
outlined_raw_atomic64_add_return_acquire(s64 i, atomic64_t *v)
{
	return raw_atomic64_add_return_acquire(i, v);
}

noinline noinstr s64
outlined_raw_atomic64_add_return_release(s64 i, atomic64_t *v)
{
	return raw_atomic64_add_return_release(i, v);
}

noinline noinstr s64
outlined_raw_atomic64_add_return_relaxed(s64 i, atomic64_t *v)
{
	return raw_atomic64_add_return_relaxed(i, v);
}

noinline noinstr s64
outlined_raw_atomic64_fetch_add(s64 i, atomic64_t *v)
{
	return raw_atomic64_fetch_add(i, v);
}

noinline noinstr s64
outlined_raw_atomic64_fetch_add_acquire(s64 i, atomic64_t *v)
{
	return raw_atomic64_fetch_add_acquire(i, v);
}

noinline noinstr s64
outlined_raw_atomic64_fetch_add_release(s64 i, atomic64_t *v)
{
	return raw_atomic64_fetch_add_release(i, v);
}

noinline noinstr s64
outlined_raw_atomic64_fetch_add_relaxed(s64 i, atomic64_t *v)
{
	return raw_atomic64_fetch_add_relaxed(i, v);
}

noinline void
outlined_atomic64_add(s64 i, atomic64_t *v)
{
	atomic64_add(i, v);
}

noinline s64
outlined_atomic64_add_return(s64 i, atomic64_t *v)
{
	return atomic64_add_return(i, v);
}

noinline s64
outlined_atomic64_add_return_acquire(s64 i, atomic64_t *v)
{
	return atomic64_add_return_acquire(i, v);
}

noinline s64
outlined_atomic64_add_return_release(s64 i, atomic64_t *v)
{
	return atomic64_add_return_release(i, v);
}

noinline s64
outlined_atomic64_add_return_relaxed(s64 i, atomic64_t *v)
{
	return atomic64_add_return_relaxed(i, v);
}

noinline s64
outlined_atomic64_fetch_add(s64 i, atomic64_t *v)
{
	return atomic64_fetch_add(i, v);
}

noinline s64
outlined_atomic64_fetch_add_acquire(s64 i, atomic64_t *v)
{
	return atomic64_fetch_add_acquire(i, v);
}

noinline s64
outlined_atomic64_fetch_add_release(s64 i, atomic64_t *v)
{
	return atomic64_fetch_add_release(i, v);
}

noinline s64
outlined_atomic64_fetch_add_relaxed(s64 i, atomic64_t *v)
{
	return atomic64_fetch_add_relaxed(i, v);
}

noinline noinstr void
outlined_raw_atomic64_sub(s64 i, atomic64_t *v)
{
	raw_atomic64_sub(i, v);
}

noinline noinstr s64
outlined_raw_atomic64_sub_return(s64 i, atomic64_t *v)
{
	return raw_atomic64_sub_return(i, v);
}

noinline noinstr s64
outlined_raw_atomic64_sub_return_acquire(s64 i, atomic64_t *v)
{
	return raw_atomic64_sub_return_acquire(i, v);
}

noinline noinstr s64
outlined_raw_atomic64_sub_return_release(s64 i, atomic64_t *v)
{
	return raw_atomic64_sub_return_release(i, v);
}

noinline noinstr s64
outlined_raw_atomic64_sub_return_relaxed(s64 i, atomic64_t *v)
{
	return raw_atomic64_sub_return_relaxed(i, v);
}

noinline noinstr s64
outlined_raw_atomic64_fetch_sub(s64 i, atomic64_t *v)
{
	return raw_atomic64_fetch_sub(i, v);
}

noinline noinstr s64
outlined_raw_atomic64_fetch_sub_acquire(s64 i, atomic64_t *v)
{
	return raw_atomic64_fetch_sub_acquire(i, v);
}

noinline noinstr s64
outlined_raw_atomic64_fetch_sub_release(s64 i, atomic64_t *v)
{
	return raw_atomic64_fetch_sub_release(i, v);
}

noinline noinstr s64
outlined_raw_atomic64_fetch_sub_relaxed(s64 i, atomic64_t *v)
{
	return raw_atomic64_fetch_sub_relaxed(i, v);
}

noinline void
outlined_atomic64_sub(s64 i, atomic64_t *v)
{
	atomic64_sub(i, v);
}

noinline s64
outlined_atomic64_sub_return(s64 i, atomic64_t *v)
{
	return atomic64_sub_return(i, v);
}

noinline s64
outlined_atomic64_sub_return_acquire(s64 i, atomic64_t *v)
{
	return atomic64_sub_return_acquire(i, v);
}

noinline s64
outlined_atomic64_sub_return_release(s64 i, atomic64_t *v)
{
	return atomic64_sub_return_release(i, v);
}

noinline s64
outlined_atomic64_sub_return_relaxed(s64 i, atomic64_t *v)
{
	return atomic64_sub_return_relaxed(i, v);
}

noinline s64
outlined_atomic64_fetch_sub(s64 i, atomic64_t *v)
{
	return atomic64_fetch_sub(i, v);
}

noinline s64
outlined_atomic64_fetch_sub_acquire(s64 i, atomic64_t *v)
{
	return atomic64_fetch_sub_acquire(i, v);
}

noinline s64
outlined_atomic64_fetch_sub_release(s64 i, atomic64_t *v)
{
	return atomic64_fetch_sub_release(i, v);
}

noinline s64
outlined_atomic64_fetch_sub_relaxed(s64 i, atomic64_t *v)
{
	return atomic64_fetch_sub_relaxed(i, v);
}

noinline noinstr void
outlined_raw_atomic64_inc(atomic64_t *v)
{
	raw_atomic64_inc(v);
}

noinline noinstr s64
outlined_raw_atomic64_inc_return(atomic64_t *v)
{
	return raw_atomic64_inc_return(v);
}

noinline noinstr s64
outlined_raw_atomic64_inc_return_acquire(atomic64_t *v)
{
	return raw_atomic64_inc_return_acquire(v);
}

noinline noinstr s64
outlined_raw_atomic64_inc_return_release(atomic64_t *v)
{
	return raw_atomic64_inc_return_release(v);
}

noinline noinstr s64
outlined_raw_atomic64_inc_return_relaxed(atomic64_t *v)
{
	return raw_atomic64_inc_return_relaxed(v);
}

noinline noinstr s64
outlined_raw_atomic64_fetch_inc(atomic64_t *v)
{
	return raw_atomic64_fetch_inc(v);
}

noinline noinstr s64
outlined_raw_atomic64_fetch_inc_acquire(atomic64_t *v)
{
	return raw_atomic64_fetch_inc_acquire(v);
}

noinline noinstr s64
outlined_raw_atomic64_fetch_inc_release(atomic64_t *v)
{
	return raw_atomic64_fetch_inc_release(v);
}

noinline noinstr s64
outlined_raw_atomic64_fetch_inc_relaxed(atomic64_t *v)
{
	return raw_atomic64_fetch_inc_relaxed(v);
}

noinline void
outlined_atomic64_inc(atomic64_t *v)
{
	atomic64_inc(v);
}

noinline s64
outlined_atomic64_inc_return(atomic64_t *v)
{
	return atomic64_inc_return(v);
}

noinline s64
outlined_atomic64_inc_return_acquire(atomic64_t *v)
{
	return atomic64_inc_return_acquire(v);
}

noinline s64
outlined_atomic64_inc_return_release(atomic64_t *v)
{
	return atomic64_inc_return_release(v);
}

noinline s64
outlined_atomic64_inc_return_relaxed(atomic64_t *v)
{
	return atomic64_inc_return_relaxed(v);
}

noinline s64
outlined_atomic64_fetch_inc(atomic64_t *v)
{
	return atomic64_fetch_inc(v);
}

noinline s64
outlined_atomic64_fetch_inc_acquire(atomic64_t *v)
{
	return atomic64_fetch_inc_acquire(v);
}

noinline s64
outlined_atomic64_fetch_inc_release(atomic64_t *v)
{
	return atomic64_fetch_inc_release(v);
}

noinline s64
outlined_atomic64_fetch_inc_relaxed(atomic64_t *v)
{
	return atomic64_fetch_inc_relaxed(v);
}

noinline noinstr void
outlined_raw_atomic64_dec(atomic64_t *v)
{
	raw_atomic64_dec(v);
}

noinline noinstr s64
outlined_raw_atomic64_dec_return(atomic64_t *v)
{
	return raw_atomic64_dec_return(v);
}

noinline noinstr s64
outlined_raw_atomic64_dec_return_acquire(atomic64_t *v)
{
	return raw_atomic64_dec_return_acquire(v);
}

noinline noinstr s64
outlined_raw_atomic64_dec_return_release(atomic64_t *v)
{
	return raw_atomic64_dec_return_release(v);
}

noinline noinstr s64
outlined_raw_atomic64_dec_return_relaxed(atomic64_t *v)
{
	return raw_atomic64_dec_return_relaxed(v);
}

noinline noinstr s64
outlined_raw_atomic64_fetch_dec(atomic64_t *v)
{
	return raw_atomic64_fetch_dec(v);
}

noinline noinstr s64
outlined_raw_atomic64_fetch_dec_acquire(atomic64_t *v)
{
	return raw_atomic64_fetch_dec_acquire(v);
}

noinline noinstr s64
outlined_raw_atomic64_fetch_dec_release(atomic64_t *v)
{
	return raw_atomic64_fetch_dec_release(v);
}

noinline noinstr s64
outlined_raw_atomic64_fetch_dec_relaxed(atomic64_t *v)
{
	return raw_atomic64_fetch_dec_relaxed(v);
}

noinline void
outlined_atomic64_dec(atomic64_t *v)
{
	atomic64_dec(v);
}

noinline s64
outlined_atomic64_dec_return(atomic64_t *v)
{
	return atomic64_dec_return(v);
}

noinline s64
outlined_atomic64_dec_return_acquire(atomic64_t *v)
{
	return atomic64_dec_return_acquire(v);
}

noinline s64
outlined_atomic64_dec_return_release(atomic64_t *v)
{
	return atomic64_dec_return_release(v);
}

noinline s64
outlined_atomic64_dec_return_relaxed(atomic64_t *v)
{
	return atomic64_dec_return_relaxed(v);
}

noinline s64
outlined_atomic64_fetch_dec(atomic64_t *v)
{
	return atomic64_fetch_dec(v);
}

noinline s64
outlined_atomic64_fetch_dec_acquire(atomic64_t *v)
{
	return atomic64_fetch_dec_acquire(v);
}

noinline s64
outlined_atomic64_fetch_dec_release(atomic64_t *v)
{
	return atomic64_fetch_dec_release(v);
}

noinline s64
outlined_atomic64_fetch_dec_relaxed(atomic64_t *v)
{
	return atomic64_fetch_dec_relaxed(v);
}

noinline noinstr void
outlined_raw_atomic64_and(s64 i, atomic64_t *v)
{
	raw_atomic64_and(i, v);
}

noinline noinstr s64
outlined_raw_atomic64_fetch_and(s64 i, atomic64_t *v)
{
	return raw_atomic64_fetch_and(i, v);
}

noinline noinstr s64
outlined_raw_atomic64_fetch_and_acquire(s64 i, atomic64_t *v)
{
	return raw_atomic64_fetch_and_acquire(i, v);
}

noinline noinstr s64
outlined_raw_atomic64_fetch_and_release(s64 i, atomic64_t *v)
{
	return raw_atomic64_fetch_and_release(i, v);
}

noinline noinstr s64
outlined_raw_atomic64_fetch_and_relaxed(s64 i, atomic64_t *v)
{
	return raw_atomic64_fetch_and_relaxed(i, v);
}

noinline void
outlined_atomic64_and(s64 i, atomic64_t *v)
{
	atomic64_and(i, v);
}

noinline s64
outlined_atomic64_fetch_and(s64 i, atomic64_t *v)
{
	return atomic64_fetch_and(i, v);
}

noinline s64
outlined_atomic64_fetch_and_acquire(s64 i, atomic64_t *v)
{
	return atomic64_fetch_and_acquire(i, v);
}

noinline s64
outlined_atomic64_fetch_and_release(s64 i, atomic64_t *v)
{
	return atomic64_fetch_and_release(i, v);
}

noinline s64
outlined_atomic64_fetch_and_relaxed(s64 i, atomic64_t *v)
{
	return atomic64_fetch_and_relaxed(i, v);
}

noinline noinstr void
outlined_raw_atomic64_andnot(s64 i, atomic64_t *v)
{
	raw_atomic64_andnot(i, v);
}

noinline noinstr s64
outlined_raw_atomic64_fetch_andnot(s64 i, atomic64_t *v)
{
	return raw_atomic64_fetch_andnot(i, v);
}

noinline noinstr s64
outlined_raw_atomic64_fetch_andnot_acquire(s64 i, atomic64_t *v)
{
	return raw_atomic64_fetch_andnot_acquire(i, v);
}

noinline noinstr s64
outlined_raw_atomic64_fetch_andnot_release(s64 i, atomic64_t *v)
{
	return raw_atomic64_fetch_andnot_release(i, v);
}

noinline noinstr s64
outlined_raw_atomic64_fetch_andnot_relaxed(s64 i, atomic64_t *v)
{
	return raw_atomic64_fetch_andnot_relaxed(i, v);
}

noinline void
outlined_atomic64_andnot(s64 i, atomic64_t *v)
{
	atomic64_andnot(i, v);
}

noinline s64
outlined_atomic64_fetch_andnot(s64 i, atomic64_t *v)
{
	return atomic64_fetch_andnot(i, v);
}

noinline s64
outlined_atomic64_fetch_andnot_acquire(s64 i, atomic64_t *v)
{
	return atomic64_fetch_andnot_acquire(i, v);
}

noinline s64
outlined_atomic64_fetch_andnot_release(s64 i, atomic64_t *v)
{
	return atomic64_fetch_andnot_release(i, v);
}

noinline s64
outlined_atomic64_fetch_andnot_relaxed(s64 i, atomic64_t *v)
{
	return atomic64_fetch_andnot_relaxed(i, v);
}

noinline noinstr void
outlined_raw_atomic64_or(s64 i, atomic64_t *v)
{
	raw_atomic64_or(i, v);
}

noinline noinstr s64
outlined_raw_atomic64_fetch_or(s64 i, atomic64_t *v)
{
	return raw_atomic64_fetch_or(i, v);
}

noinline noinstr s64
outlined_raw_atomic64_fetch_or_acquire(s64 i, atomic64_t *v)
{
	return raw_atomic64_fetch_or_acquire(i, v);
}

noinline noinstr s64
outlined_raw_atomic64_fetch_or_release(s64 i, atomic64_t *v)
{
	return raw_atomic64_fetch_or_release(i, v);
}

noinline noinstr s64
outlined_raw_atomic64_fetch_or_relaxed(s64 i, atomic64_t *v)
{
	return raw_atomic64_fetch_or_relaxed(i, v);
}

noinline void
outlined_atomic64_or(s64 i, atomic64_t *v)
{
	atomic64_or(i, v);
}

noinline s64
outlined_atomic64_fetch_or(s64 i, atomic64_t *v)
{
	return atomic64_fetch_or(i, v);
}

noinline s64
outlined_atomic64_fetch_or_acquire(s64 i, atomic64_t *v)
{
	return atomic64_fetch_or_acquire(i, v);
}

noinline s64
outlined_atomic64_fetch_or_release(s64 i, atomic64_t *v)
{
	return atomic64_fetch_or_release(i, v);
}

noinline s64
outlined_atomic64_fetch_or_relaxed(s64 i, atomic64_t *v)
{
	return atomic64_fetch_or_relaxed(i, v);
}

noinline noinstr void
outlined_raw_atomic64_xor(s64 i, atomic64_t *v)
{
	raw_atomic64_xor(i, v);
}

noinline noinstr s64
outlined_raw_atomic64_fetch_xor(s64 i, atomic64_t *v)
{
	return raw_atomic64_fetch_xor(i, v);
}

noinline noinstr s64
outlined_raw_atomic64_fetch_xor_acquire(s64 i, atomic64_t *v)
{
	return raw_atomic64_fetch_xor_acquire(i, v);
}

noinline noinstr s64
outlined_raw_atomic64_fetch_xor_release(s64 i, atomic64_t *v)
{
	return raw_atomic64_fetch_xor_release(i, v);
}

noinline noinstr s64
outlined_raw_atomic64_fetch_xor_relaxed(s64 i, atomic64_t *v)
{
	return raw_atomic64_fetch_xor_relaxed(i, v);
}

noinline void
outlined_atomic64_xor(s64 i, atomic64_t *v)
{
	atomic64_xor(i, v);
}

noinline s64
outlined_atomic64_fetch_xor(s64 i, atomic64_t *v)
{
	return atomic64_fetch_xor(i, v);
}

noinline s64
outlined_atomic64_fetch_xor_acquire(s64 i, atomic64_t *v)
{
	return atomic64_fetch_xor_acquire(i, v);
}

noinline s64
outlined_atomic64_fetch_xor_release(s64 i, atomic64_t *v)
{
	return atomic64_fetch_xor_release(i, v);
}

noinline s64
outlined_atomic64_fetch_xor_relaxed(s64 i, atomic64_t *v)
{
	return atomic64_fetch_xor_relaxed(i, v);
}

noinline noinstr s64
outlined_raw_atomic64_xchg(atomic64_t *v, s64 new)
{
	return raw_atomic64_xchg(v, new);
}

noinline noinstr s64
outlined_raw_atomic64_xchg_acquire(atomic64_t *v, s64 new)
{
	return raw_atomic64_xchg_acquire(v, new);
}

noinline noinstr s64
outlined_raw_atomic64_xchg_release(atomic64_t *v, s64 new)
{
	return raw_atomic64_xchg_release(v, new);
}

noinline noinstr s64
outlined_raw_atomic64_xchg_relaxed(atomic64_t *v, s64 new)
{
	return raw_atomic64_xchg_relaxed(v, new);
}

noinline s64
outlined_atomic64_xchg(atomic64_t *v, s64 new)
{
	return atomic64_xchg(v, new);
}

noinline s64
outlined_atomic64_xchg_acquire(atomic64_t *v, s64 new)
{
	return atomic64_xchg_acquire(v, new);
}

noinline s64
outlined_atomic64_xchg_release(atomic64_t *v, s64 new)
{
	return atomic64_xchg_release(v, new);
}

noinline s64
outlined_atomic64_xchg_relaxed(atomic64_t *v, s64 new)
{
	return atomic64_xchg_relaxed(v, new);
}

noinline noinstr s64
outlined_raw_atomic64_cmpxchg(atomic64_t *v, s64 old, s64 new)
{
	return raw_atomic64_cmpxchg(v, old, new);
}

noinline noinstr s64
outlined_raw_atomic64_cmpxchg_acquire(atomic64_t *v, s64 old, s64 new)
{
	return raw_atomic64_cmpxchg_acquire(v, old, new);
}

noinline noinstr s64
outlined_raw_atomic64_cmpxchg_release(atomic64_t *v, s64 old, s64 new)
{
	return raw_atomic64_cmpxchg_release(v, old, new);
}

noinline noinstr s64
outlined_raw_atomic64_cmpxchg_relaxed(atomic64_t *v, s64 old, s64 new)
{
	return raw_atomic64_cmpxchg_relaxed(v, old, new);
}

noinline s64
outlined_atomic64_cmpxchg(atomic64_t *v, s64 old, s64 new)
{
	return atomic64_cmpxchg(v, old, new);
}

noinline s64
outlined_atomic64_cmpxchg_acquire(atomic64_t *v, s64 old, s64 new)
{
	return atomic64_cmpxchg_acquire(v, old, new);
}

noinline s64
outlined_atomic64_cmpxchg_release(atomic64_t *v, s64 old, s64 new)
{
	return atomic64_cmpxchg_release(v, old, new);
}

noinline s64
outlined_atomic64_cmpxchg_relaxed(atomic64_t *v, s64 old, s64 new)
{
	return atomic64_cmpxchg_relaxed(v, old, new);
}

noinline noinstr bool
outlined_raw_atomic64_try_cmpxchg(atomic64_t *v, s64 *old, s64 new)
{
	return raw_atomic64_try_cmpxchg(v, old, new);
}

noinline noinstr bool
outlined_raw_atomic64_try_cmpxchg_acquire(atomic64_t *v, s64 *old, s64 new)
{
	return raw_atomic64_try_cmpxchg_acquire(v, old, new);
}

noinline noinstr bool
outlined_raw_atomic64_try_cmpxchg_release(atomic64_t *v, s64 *old, s64 new)
{
	return raw_atomic64_try_cmpxchg_release(v, old, new);
}

noinline noinstr bool
outlined_raw_atomic64_try_cmpxchg_relaxed(atomic64_t *v, s64 *old, s64 new)
{
	return raw_atomic64_try_cmpxchg_relaxed(v, old, new);
}

noinline bool
outlined_atomic64_try_cmpxchg(atomic64_t *v, s64 *old, s64 new)
{
	return atomic64_try_cmpxchg(v, old, new);
}

noinline bool
outlined_atomic64_try_cmpxchg_acquire(atomic64_t *v, s64 *old, s64 new)
{
	return atomic64_try_cmpxchg_acquire(v, old, new);
}

noinline bool
outlined_atomic64_try_cmpxchg_release(atomic64_t *v, s64 *old, s64 new)
{
	return atomic64_try_cmpxchg_release(v, old, new);
}

noinline bool
outlined_atomic64_try_cmpxchg_relaxed(atomic64_t *v, s64 *old, s64 new)
{
	return atomic64_try_cmpxchg_relaxed(v, old, new);
}

noinline noinstr bool
outlined_raw_atomic64_sub_and_test(s64 i, atomic64_t *v)
{
	return raw_atomic64_sub_and_test(i, v);
}

noinline bool
outlined_atomic64_sub_and_test(s64 i, atomic64_t *v)
{
	return atomic64_sub_and_test(i, v);
}

noinline noinstr bool
outlined_raw_atomic64_dec_and_test(atomic64_t *v)
{
	return raw_atomic64_dec_and_test(v);
}

noinline bool
outlined_atomic64_dec_and_test(atomic64_t *v)
{
	return atomic64_dec_and_test(v);
}

noinline noinstr bool
outlined_raw_atomic64_inc_and_test(atomic64_t *v)
{
	return raw_atomic64_inc_and_test(v);
}

noinline bool
outlined_atomic64_inc_and_test(atomic64_t *v)
{
	return atomic64_inc_and_test(v);
}

noinline noinstr bool
outlined_raw_atomic64_add_negative(s64 i, atomic64_t *v)
{
	return raw_atomic64_add_negative(i, v);
}

noinline noinstr bool
outlined_raw_atomic64_add_negative_acquire(s64 i, atomic64_t *v)
{
	return raw_atomic64_add_negative_acquire(i, v);
}

noinline noinstr bool
outlined_raw_atomic64_add_negative_release(s64 i, atomic64_t *v)
{
	return raw_atomic64_add_negative_release(i, v);
}

noinline noinstr bool
outlined_raw_atomic64_add_negative_relaxed(s64 i, atomic64_t *v)
{
	return raw_atomic64_add_negative_relaxed(i, v);
}

noinline bool
outlined_atomic64_add_negative(s64 i, atomic64_t *v)
{
	return atomic64_add_negative(i, v);
}

noinline bool
outlined_atomic64_add_negative_acquire(s64 i, atomic64_t *v)
{
	return atomic64_add_negative_acquire(i, v);
}

noinline bool
outlined_atomic64_add_negative_release(s64 i, atomic64_t *v)
{
	return atomic64_add_negative_release(i, v);
}

noinline bool
outlined_atomic64_add_negative_relaxed(s64 i, atomic64_t *v)
{
	return atomic64_add_negative_relaxed(i, v);
}

noinline noinstr s64
outlined_raw_atomic64_fetch_add_unless(atomic64_t *v, s64 a, s64 u)
{
	return raw_atomic64_fetch_add_unless(v, a, u);
}

noinline noinstr bool
outlined_raw_atomic64_add_unless(atomic64_t *v, s64 a, s64 u)
{
	return raw_atomic64_add_unless(v, a, u);
}

noinline s64
outlined_atomic64_fetch_add_unless(atomic64_t *v, s64 a, s64 u)
{
	return atomic64_fetch_add_unless(v, a, u);
}

noinline bool
outlined_atomic64_add_unless(atomic64_t *v, s64 a, s64 u)
{
	return atomic64_add_unless(v, a, u);
}

noinline noinstr bool
outlined_raw_atomic64_inc_not_zero(atomic64_t *v)
{
	return raw_atomic64_inc_not_zero(v);
}

noinline bool
outlined_atomic64_inc_not_zero(atomic64_t *v)
{
	return atomic64_inc_not_zero(v);
}

noinline noinstr bool
outlined_raw_atomic64_inc_unless_negative(atomic64_t *v)
{
	return raw_atomic64_inc_unless_negative(v);
}

noinline bool
outlined_atomic64_inc_unless_negative(atomic64_t *v)
{
	return atomic64_inc_unless_negative(v);
}

noinline noinstr bool
outlined_raw_atomic64_dec_unless_positive(atomic64_t *v)
{
	return raw_atomic64_dec_unless_positive(v);
}

noinline bool
outlined_atomic64_dec_unless_positive(atomic64_t *v)
{
	return atomic64_dec_unless_positive(v);
}

noinline noinstr s64
outlined_raw_atomic64_dec_if_positive(atomic64_t *v)
{
	return raw_atomic64_dec_if_positive(v);
}

noinline s64
outlined_atomic64_dec_if_positive(atomic64_t *v)
{
	return atomic64_dec_if_positive(v);
}

noinline noinstr long
outlined_raw_atomic_long_read(const atomic_long_t *v)
{
	return raw_atomic_long_read(v);
}

noinline noinstr long
outlined_raw_atomic_long_read_acquire(const atomic_long_t *v)
{
	return raw_atomic_long_read_acquire(v);
}

noinline long
outlined_atomic_long_read(const atomic_long_t *v)
{
	return atomic_long_read(v);
}

noinline long
outlined_atomic_long_read_acquire(const atomic_long_t *v)
{
	return atomic_long_read_acquire(v);
}

noinline noinstr void
outlined_raw_atomic_long_set(atomic_long_t *v, long i)
{
	raw_atomic_long_set(v, i);
}

noinline noinstr void
outlined_raw_atomic_long_set_release(atomic_long_t *v, long i)
{
	raw_atomic_long_set_release(v, i);
}

noinline void
outlined_atomic_long_set(atomic_long_t *v, long i)
{
	atomic_long_set(v, i);
}

noinline void
outlined_atomic_long_set_release(atomic_long_t *v, long i)
{
	atomic_long_set_release(v, i);
}

noinline noinstr void
outlined_raw_atomic_long_add(long i, atomic_long_t *v)
{
	raw_atomic_long_add(i, v);
}

noinline noinstr long
outlined_raw_atomic_long_add_return(long i, atomic_long_t *v)
{
	return raw_atomic_long_add_return(i, v);
}

noinline noinstr long
outlined_raw_atomic_long_add_return_acquire(long i, atomic_long_t *v)
{
	return raw_atomic_long_add_return_acquire(i, v);
}

noinline noinstr long
outlined_raw_atomic_long_add_return_release(long i, atomic_long_t *v)
{
	return raw_atomic_long_add_return_release(i, v);
}

noinline noinstr long
outlined_raw_atomic_long_add_return_relaxed(long i, atomic_long_t *v)
{
	return raw_atomic_long_add_return_relaxed(i, v);
}

noinline noinstr long
outlined_raw_atomic_long_fetch_add(long i, atomic_long_t *v)
{
	return raw_atomic_long_fetch_add(i, v);
}

noinline noinstr long
outlined_raw_atomic_long_fetch_add_acquire(long i, atomic_long_t *v)
{
	return raw_atomic_long_fetch_add_acquire(i, v);
}

noinline noinstr long
outlined_raw_atomic_long_fetch_add_release(long i, atomic_long_t *v)
{
	return raw_atomic_long_fetch_add_release(i, v);
}

noinline noinstr long
outlined_raw_atomic_long_fetch_add_relaxed(long i, atomic_long_t *v)
{
	return raw_atomic_long_fetch_add_relaxed(i, v);
}

noinline void
outlined_atomic_long_add(long i, atomic_long_t *v)
{
	atomic_long_add(i, v);
}

noinline long
outlined_atomic_long_add_return(long i, atomic_long_t *v)
{
	return atomic_long_add_return(i, v);
}

noinline long
outlined_atomic_long_add_return_acquire(long i, atomic_long_t *v)
{
	return atomic_long_add_return_acquire(i, v);
}

noinline long
outlined_atomic_long_add_return_release(long i, atomic_long_t *v)
{
	return atomic_long_add_return_release(i, v);
}

noinline long
outlined_atomic_long_add_return_relaxed(long i, atomic_long_t *v)
{
	return atomic_long_add_return_relaxed(i, v);
}

noinline long
outlined_atomic_long_fetch_add(long i, atomic_long_t *v)
{
	return atomic_long_fetch_add(i, v);
}

noinline long
outlined_atomic_long_fetch_add_acquire(long i, atomic_long_t *v)
{
	return atomic_long_fetch_add_acquire(i, v);
}

noinline long
outlined_atomic_long_fetch_add_release(long i, atomic_long_t *v)
{
	return atomic_long_fetch_add_release(i, v);
}

noinline long
outlined_atomic_long_fetch_add_relaxed(long i, atomic_long_t *v)
{
	return atomic_long_fetch_add_relaxed(i, v);
}

noinline noinstr void
outlined_raw_atomic_long_sub(long i, atomic_long_t *v)
{
	raw_atomic_long_sub(i, v);
}

noinline noinstr long
outlined_raw_atomic_long_sub_return(long i, atomic_long_t *v)
{
	return raw_atomic_long_sub_return(i, v);
}

noinline noinstr long
outlined_raw_atomic_long_sub_return_acquire(long i, atomic_long_t *v)
{
	return raw_atomic_long_sub_return_acquire(i, v);
}

noinline noinstr long
outlined_raw_atomic_long_sub_return_release(long i, atomic_long_t *v)
{
	return raw_atomic_long_sub_return_release(i, v);
}

noinline noinstr long
outlined_raw_atomic_long_sub_return_relaxed(long i, atomic_long_t *v)
{
	return raw_atomic_long_sub_return_relaxed(i, v);
}

noinline noinstr long
outlined_raw_atomic_long_fetch_sub(long i, atomic_long_t *v)
{
	return raw_atomic_long_fetch_sub(i, v);
}

noinline noinstr long
outlined_raw_atomic_long_fetch_sub_acquire(long i, atomic_long_t *v)
{
	return raw_atomic_long_fetch_sub_acquire(i, v);
}

noinline noinstr long
outlined_raw_atomic_long_fetch_sub_release(long i, atomic_long_t *v)
{
	return raw_atomic_long_fetch_sub_release(i, v);
}

noinline noinstr long
outlined_raw_atomic_long_fetch_sub_relaxed(long i, atomic_long_t *v)
{
	return raw_atomic_long_fetch_sub_relaxed(i, v);
}

noinline void
outlined_atomic_long_sub(long i, atomic_long_t *v)
{
	atomic_long_sub(i, v);
}

noinline long
outlined_atomic_long_sub_return(long i, atomic_long_t *v)
{
	return atomic_long_sub_return(i, v);
}

noinline long
outlined_atomic_long_sub_return_acquire(long i, atomic_long_t *v)
{
	return atomic_long_sub_return_acquire(i, v);
}

noinline long
outlined_atomic_long_sub_return_release(long i, atomic_long_t *v)
{
	return atomic_long_sub_return_release(i, v);
}

noinline long
outlined_atomic_long_sub_return_relaxed(long i, atomic_long_t *v)
{
	return atomic_long_sub_return_relaxed(i, v);
}

noinline long
outlined_atomic_long_fetch_sub(long i, atomic_long_t *v)
{
	return atomic_long_fetch_sub(i, v);
}

noinline long
outlined_atomic_long_fetch_sub_acquire(long i, atomic_long_t *v)
{
	return atomic_long_fetch_sub_acquire(i, v);
}

noinline long
outlined_atomic_long_fetch_sub_release(long i, atomic_long_t *v)
{
	return atomic_long_fetch_sub_release(i, v);
}

noinline long
outlined_atomic_long_fetch_sub_relaxed(long i, atomic_long_t *v)
{
	return atomic_long_fetch_sub_relaxed(i, v);
}

noinline noinstr void
outlined_raw_atomic_long_inc(atomic_long_t *v)
{
	raw_atomic_long_inc(v);
}

noinline noinstr long
outlined_raw_atomic_long_inc_return(atomic_long_t *v)
{
	return raw_atomic_long_inc_return(v);
}

noinline noinstr long
outlined_raw_atomic_long_inc_return_acquire(atomic_long_t *v)
{
	return raw_atomic_long_inc_return_acquire(v);
}

noinline noinstr long
outlined_raw_atomic_long_inc_return_release(atomic_long_t *v)
{
	return raw_atomic_long_inc_return_release(v);
}

noinline noinstr long
outlined_raw_atomic_long_inc_return_relaxed(atomic_long_t *v)
{
	return raw_atomic_long_inc_return_relaxed(v);
}

noinline noinstr long
outlined_raw_atomic_long_fetch_inc(atomic_long_t *v)
{
	return raw_atomic_long_fetch_inc(v);
}

noinline noinstr long
outlined_raw_atomic_long_fetch_inc_acquire(atomic_long_t *v)
{
	return raw_atomic_long_fetch_inc_acquire(v);
}

noinline noinstr long
outlined_raw_atomic_long_fetch_inc_release(atomic_long_t *v)
{
	return raw_atomic_long_fetch_inc_release(v);
}

noinline noinstr long
outlined_raw_atomic_long_fetch_inc_relaxed(atomic_long_t *v)
{
	return raw_atomic_long_fetch_inc_relaxed(v);
}

noinline void
outlined_atomic_long_inc(atomic_long_t *v)
{
	atomic_long_inc(v);
}

noinline long
outlined_atomic_long_inc_return(atomic_long_t *v)
{
	return atomic_long_inc_return(v);
}

noinline long
outlined_atomic_long_inc_return_acquire(atomic_long_t *v)
{
	return atomic_long_inc_return_acquire(v);
}

noinline long
outlined_atomic_long_inc_return_release(atomic_long_t *v)
{
	return atomic_long_inc_return_release(v);
}

noinline long
outlined_atomic_long_inc_return_relaxed(atomic_long_t *v)
{
	return atomic_long_inc_return_relaxed(v);
}

noinline long
outlined_atomic_long_fetch_inc(atomic_long_t *v)
{
	return atomic_long_fetch_inc(v);
}

noinline long
outlined_atomic_long_fetch_inc_acquire(atomic_long_t *v)
{
	return atomic_long_fetch_inc_acquire(v);
}

noinline long
outlined_atomic_long_fetch_inc_release(atomic_long_t *v)
{
	return atomic_long_fetch_inc_release(v);
}

noinline long
outlined_atomic_long_fetch_inc_relaxed(atomic_long_t *v)
{
	return atomic_long_fetch_inc_relaxed(v);
}

noinline noinstr void
outlined_raw_atomic_long_dec(atomic_long_t *v)
{
	raw_atomic_long_dec(v);
}

noinline noinstr long
outlined_raw_atomic_long_dec_return(atomic_long_t *v)
{
	return raw_atomic_long_dec_return(v);
}

noinline noinstr long
outlined_raw_atomic_long_dec_return_acquire(atomic_long_t *v)
{
	return raw_atomic_long_dec_return_acquire(v);
}

noinline noinstr long
outlined_raw_atomic_long_dec_return_release(atomic_long_t *v)
{
	return raw_atomic_long_dec_return_release(v);
}

noinline noinstr long
outlined_raw_atomic_long_dec_return_relaxed(atomic_long_t *v)
{
	return raw_atomic_long_dec_return_relaxed(v);
}

noinline noinstr long
outlined_raw_atomic_long_fetch_dec(atomic_long_t *v)
{
	return raw_atomic_long_fetch_dec(v);
}

noinline noinstr long
outlined_raw_atomic_long_fetch_dec_acquire(atomic_long_t *v)
{
	return raw_atomic_long_fetch_dec_acquire(v);
}

noinline noinstr long
outlined_raw_atomic_long_fetch_dec_release(atomic_long_t *v)
{
	return raw_atomic_long_fetch_dec_release(v);
}

noinline noinstr long
outlined_raw_atomic_long_fetch_dec_relaxed(atomic_long_t *v)
{
	return raw_atomic_long_fetch_dec_relaxed(v);
}

noinline void
outlined_atomic_long_dec(atomic_long_t *v)
{
	atomic_long_dec(v);
}

noinline long
outlined_atomic_long_dec_return(atomic_long_t *v)
{
	return atomic_long_dec_return(v);
}

noinline long
outlined_atomic_long_dec_return_acquire(atomic_long_t *v)
{
	return atomic_long_dec_return_acquire(v);
}

noinline long
outlined_atomic_long_dec_return_release(atomic_long_t *v)
{
	return atomic_long_dec_return_release(v);
}

noinline long
outlined_atomic_long_dec_return_relaxed(atomic_long_t *v)
{
	return atomic_long_dec_return_relaxed(v);
}

noinline long
outlined_atomic_long_fetch_dec(atomic_long_t *v)
{
	return atomic_long_fetch_dec(v);
}

noinline long
outlined_atomic_long_fetch_dec_acquire(atomic_long_t *v)
{
	return atomic_long_fetch_dec_acquire(v);
}

noinline long
outlined_atomic_long_fetch_dec_release(atomic_long_t *v)
{
	return atomic_long_fetch_dec_release(v);
}

noinline long
outlined_atomic_long_fetch_dec_relaxed(atomic_long_t *v)
{
	return atomic_long_fetch_dec_relaxed(v);
}

noinline noinstr void
outlined_raw_atomic_long_and(long i, atomic_long_t *v)
{
	raw_atomic_long_and(i, v);
}

noinline noinstr long
outlined_raw_atomic_long_fetch_and(long i, atomic_long_t *v)
{
	return raw_atomic_long_fetch_and(i, v);
}

noinline noinstr long
outlined_raw_atomic_long_fetch_and_acquire(long i, atomic_long_t *v)
{
	return raw_atomic_long_fetch_and_acquire(i, v);
}

noinline noinstr long
outlined_raw_atomic_long_fetch_and_release(long i, atomic_long_t *v)
{
	return raw_atomic_long_fetch_and_release(i, v);
}

noinline noinstr long
outlined_raw_atomic_long_fetch_and_relaxed(long i, atomic_long_t *v)
{
	return raw_atomic_long_fetch_and_relaxed(i, v);
}

noinline void
outlined_atomic_long_and(long i, atomic_long_t *v)
{
	atomic_long_and(i, v);
}

noinline long
outlined_atomic_long_fetch_and(long i, atomic_long_t *v)
{
	return atomic_long_fetch_and(i, v);
}

noinline long
outlined_atomic_long_fetch_and_acquire(long i, atomic_long_t *v)
{
	return atomic_long_fetch_and_acquire(i, v);
}

noinline long
outlined_atomic_long_fetch_and_release(long i, atomic_long_t *v)
{
	return atomic_long_fetch_and_release(i, v);
}

noinline long
outlined_atomic_long_fetch_and_relaxed(long i, atomic_long_t *v)
{
	return atomic_long_fetch_and_relaxed(i, v);
}

noinline noinstr void
outlined_raw_atomic_long_andnot(long i, atomic_long_t *v)
{
	raw_atomic_long_andnot(i, v);
}

noinline noinstr long
outlined_raw_atomic_long_fetch_andnot(long i, atomic_long_t *v)
{
	return raw_atomic_long_fetch_andnot(i, v);
}

noinline noinstr long
outlined_raw_atomic_long_fetch_andnot_acquire(long i, atomic_long_t *v)
{
	return raw_atomic_long_fetch_andnot_acquire(i, v);
}

noinline noinstr long
outlined_raw_atomic_long_fetch_andnot_release(long i, atomic_long_t *v)
{
	return raw_atomic_long_fetch_andnot_release(i, v);
}

noinline noinstr long
outlined_raw_atomic_long_fetch_andnot_relaxed(long i, atomic_long_t *v)
{
	return raw_atomic_long_fetch_andnot_relaxed(i, v);
}

noinline void
outlined_atomic_long_andnot(long i, atomic_long_t *v)
{
	atomic_long_andnot(i, v);
}

noinline long
outlined_atomic_long_fetch_andnot(long i, atomic_long_t *v)
{
	return atomic_long_fetch_andnot(i, v);
}

noinline long
outlined_atomic_long_fetch_andnot_acquire(long i, atomic_long_t *v)
{
	return atomic_long_fetch_andnot_acquire(i, v);
}

noinline long
outlined_atomic_long_fetch_andnot_release(long i, atomic_long_t *v)
{
	return atomic_long_fetch_andnot_release(i, v);
}

noinline long
outlined_atomic_long_fetch_andnot_relaxed(long i, atomic_long_t *v)
{
	return atomic_long_fetch_andnot_relaxed(i, v);
}

noinline noinstr void
outlined_raw_atomic_long_or(long i, atomic_long_t *v)
{
	raw_atomic_long_or(i, v);
}

noinline noinstr long
outlined_raw_atomic_long_fetch_or(long i, atomic_long_t *v)
{
	return raw_atomic_long_fetch_or(i, v);
}

noinline noinstr long
outlined_raw_atomic_long_fetch_or_acquire(long i, atomic_long_t *v)
{
	return raw_atomic_long_fetch_or_acquire(i, v);
}

noinline noinstr long
outlined_raw_atomic_long_fetch_or_release(long i, atomic_long_t *v)
{
	return raw_atomic_long_fetch_or_release(i, v);
}

noinline noinstr long
outlined_raw_atomic_long_fetch_or_relaxed(long i, atomic_long_t *v)
{
	return raw_atomic_long_fetch_or_relaxed(i, v);
}

noinline void
outlined_atomic_long_or(long i, atomic_long_t *v)
{
	atomic_long_or(i, v);
}

noinline long
outlined_atomic_long_fetch_or(long i, atomic_long_t *v)
{
	return atomic_long_fetch_or(i, v);
}

noinline long
outlined_atomic_long_fetch_or_acquire(long i, atomic_long_t *v)
{
	return atomic_long_fetch_or_acquire(i, v);
}

noinline long
outlined_atomic_long_fetch_or_release(long i, atomic_long_t *v)
{
	return atomic_long_fetch_or_release(i, v);
}

noinline long
outlined_atomic_long_fetch_or_relaxed(long i, atomic_long_t *v)
{
	return atomic_long_fetch_or_relaxed(i, v);
}

noinline noinstr void
outlined_raw_atomic_long_xor(long i, atomic_long_t *v)
{
	raw_atomic_long_xor(i, v);
}

noinline noinstr long
outlined_raw_atomic_long_fetch_xor(long i, atomic_long_t *v)
{
	return raw_atomic_long_fetch_xor(i, v);
}

noinline noinstr long
outlined_raw_atomic_long_fetch_xor_acquire(long i, atomic_long_t *v)
{
	return raw_atomic_long_fetch_xor_acquire(i, v);
}

noinline noinstr long
outlined_raw_atomic_long_fetch_xor_release(long i, atomic_long_t *v)
{
	return raw_atomic_long_fetch_xor_release(i, v);
}

noinline noinstr long
outlined_raw_atomic_long_fetch_xor_relaxed(long i, atomic_long_t *v)
{
	return raw_atomic_long_fetch_xor_relaxed(i, v);
}

noinline void
outlined_atomic_long_xor(long i, atomic_long_t *v)
{
	atomic_long_xor(i, v);
}

noinline long
outlined_atomic_long_fetch_xor(long i, atomic_long_t *v)
{
	return atomic_long_fetch_xor(i, v);
}

noinline long
outlined_atomic_long_fetch_xor_acquire(long i, atomic_long_t *v)
{
	return atomic_long_fetch_xor_acquire(i, v);
}

noinline long
outlined_atomic_long_fetch_xor_release(long i, atomic_long_t *v)
{
	return atomic_long_fetch_xor_release(i, v);
}

noinline long
outlined_atomic_long_fetch_xor_relaxed(long i, atomic_long_t *v)
{
	return atomic_long_fetch_xor_relaxed(i, v);
}

noinline noinstr long
outlined_raw_atomic_long_xchg(atomic_long_t *v, long new)
{
	return raw_atomic_long_xchg(v, new);
}

noinline noinstr long
outlined_raw_atomic_long_xchg_acquire(atomic_long_t *v, long new)
{
	return raw_atomic_long_xchg_acquire(v, new);
}

noinline noinstr long
outlined_raw_atomic_long_xchg_release(atomic_long_t *v, long new)
{
	return raw_atomic_long_xchg_release(v, new);
}

noinline noinstr long
outlined_raw_atomic_long_xchg_relaxed(atomic_long_t *v, long new)
{
	return raw_atomic_long_xchg_relaxed(v, new);
}

noinline long
outlined_atomic_long_xchg(atomic_long_t *v, long new)
{
	return atomic_long_xchg(v, new);
}

noinline long
outlined_atomic_long_xchg_acquire(atomic_long_t *v, long new)
{
	return atomic_long_xchg_acquire(v, new);
}

noinline long
outlined_atomic_long_xchg_release(atomic_long_t *v, long new)
{
	return atomic_long_xchg_release(v, new);
}

noinline long
outlined_atomic_long_xchg_relaxed(atomic_long_t *v, long new)
{
	return atomic_long_xchg_relaxed(v, new);
}

noinline noinstr long
outlined_raw_atomic_long_cmpxchg(atomic_long_t *v, long old, long new)
{
	return raw_atomic_long_cmpxchg(v, old, new);
}

noinline noinstr long
outlined_raw_atomic_long_cmpxchg_acquire(atomic_long_t *v, long old, long new)
{
	return raw_atomic_long_cmpxchg_acquire(v, old, new);
}

noinline noinstr long
outlined_raw_atomic_long_cmpxchg_release(atomic_long_t *v, long old, long new)
{
	return raw_atomic_long_cmpxchg_release(v, old, new);
}

noinline noinstr long
outlined_raw_atomic_long_cmpxchg_relaxed(atomic_long_t *v, long old, long new)
{
	return raw_atomic_long_cmpxchg_relaxed(v, old, new);
}

noinline long
outlined_atomic_long_cmpxchg(atomic_long_t *v, long old, long new)
{
	return atomic_long_cmpxchg(v, old, new);
}

noinline long
outlined_atomic_long_cmpxchg_acquire(atomic_long_t *v, long old, long new)
{
	return atomic_long_cmpxchg_acquire(v, old, new);
}

noinline long
outlined_atomic_long_cmpxchg_release(atomic_long_t *v, long old, long new)
{
	return atomic_long_cmpxchg_release(v, old, new);
}

noinline long
outlined_atomic_long_cmpxchg_relaxed(atomic_long_t *v, long old, long new)
{
	return atomic_long_cmpxchg_relaxed(v, old, new);
}

noinline noinstr bool
outlined_raw_atomic_long_try_cmpxchg(atomic_long_t *v, long *old, long new)
{
	return raw_atomic_long_try_cmpxchg(v, old, new);
}

noinline noinstr bool
outlined_raw_atomic_long_try_cmpxchg_acquire(atomic_long_t *v, long *old, long new)
{
	return raw_atomic_long_try_cmpxchg_acquire(v, old, new);
}

noinline noinstr bool
outlined_raw_atomic_long_try_cmpxchg_release(atomic_long_t *v, long *old, long new)
{
	return raw_atomic_long_try_cmpxchg_release(v, old, new);
}

noinline noinstr bool
outlined_raw_atomic_long_try_cmpxchg_relaxed(atomic_long_t *v, long *old, long new)
{
	return raw_atomic_long_try_cmpxchg_relaxed(v, old, new);
}

noinline bool
outlined_atomic_long_try_cmpxchg(atomic_long_t *v, long *old, long new)
{
	return atomic_long_try_cmpxchg(v, old, new);
}

noinline bool
outlined_atomic_long_try_cmpxchg_acquire(atomic_long_t *v, long *old, long new)
{
	return atomic_long_try_cmpxchg_acquire(v, old, new);
}

noinline bool
outlined_atomic_long_try_cmpxchg_release(atomic_long_t *v, long *old, long new)
{
	return atomic_long_try_cmpxchg_release(v, old, new);
}

noinline bool
outlined_atomic_long_try_cmpxchg_relaxed(atomic_long_t *v, long *old, long new)
{
	return atomic_long_try_cmpxchg_relaxed(v, old, new);
}

noinline noinstr bool
outlined_raw_atomic_long_sub_and_test(long i, atomic_long_t *v)
{
	return raw_atomic_long_sub_and_test(i, v);
}

noinline bool
outlined_atomic_long_sub_and_test(long i, atomic_long_t *v)
{
	return atomic_long_sub_and_test(i, v);
}

noinline noinstr bool
outlined_raw_atomic_long_dec_and_test(atomic_long_t *v)
{
	return raw_atomic_long_dec_and_test(v);
}

noinline bool
outlined_atomic_long_dec_and_test(atomic_long_t *v)
{
	return atomic_long_dec_and_test(v);
}

noinline noinstr bool
outlined_raw_atomic_long_inc_and_test(atomic_long_t *v)
{
	return raw_atomic_long_inc_and_test(v);
}

noinline bool
outlined_atomic_long_inc_and_test(atomic_long_t *v)
{
	return atomic_long_inc_and_test(v);
}

noinline noinstr bool
outlined_raw_atomic_long_add_negative(long i, atomic_long_t *v)
{
	return raw_atomic_long_add_negative(i, v);
}

noinline noinstr bool
outlined_raw_atomic_long_add_negative_acquire(long i, atomic_long_t *v)
{
	return raw_atomic_long_add_negative_acquire(i, v);
}

noinline noinstr bool
outlined_raw_atomic_long_add_negative_release(long i, atomic_long_t *v)
{
	return raw_atomic_long_add_negative_release(i, v);
}

noinline noinstr bool
outlined_raw_atomic_long_add_negative_relaxed(long i, atomic_long_t *v)
{
	return raw_atomic_long_add_negative_relaxed(i, v);
}

noinline bool
outlined_atomic_long_add_negative(long i, atomic_long_t *v)
{
	return atomic_long_add_negative(i, v);
}

noinline bool
outlined_atomic_long_add_negative_acquire(long i, atomic_long_t *v)
{
	return atomic_long_add_negative_acquire(i, v);
}

noinline bool
outlined_atomic_long_add_negative_release(long i, atomic_long_t *v)
{
	return atomic_long_add_negative_release(i, v);
}

noinline bool
outlined_atomic_long_add_negative_relaxed(long i, atomic_long_t *v)
{
	return atomic_long_add_negative_relaxed(i, v);
}

noinline noinstr long
outlined_raw_atomic_long_fetch_add_unless(atomic_long_t *v, long a, long u)
{
	return raw_atomic_long_fetch_add_unless(v, a, u);
}

noinline noinstr bool
outlined_raw_atomic_long_add_unless(atomic_long_t *v, long a, long u)
{
	return raw_atomic_long_add_unless(v, a, u);
}

noinline long
outlined_atomic_long_fetch_add_unless(atomic_long_t *v, long a, long u)
{
	return atomic_long_fetch_add_unless(v, a, u);
}

noinline bool
outlined_atomic_long_add_unless(atomic_long_t *v, long a, long u)
{
	return atomic_long_add_unless(v, a, u);
}

noinline noinstr bool
outlined_raw_atomic_long_inc_not_zero(atomic_long_t *v)
{
	return raw_atomic_long_inc_not_zero(v);
}

noinline bool
outlined_atomic_long_inc_not_zero(atomic_long_t *v)
{
	return atomic_long_inc_not_zero(v);
}

noinline noinstr bool
outlined_raw_atomic_long_inc_unless_negative(atomic_long_t *v)
{
	return raw_atomic_long_inc_unless_negative(v);
}

noinline bool
outlined_atomic_long_inc_unless_negative(atomic_long_t *v)
{
	return atomic_long_inc_unless_negative(v);
}

noinline noinstr bool
outlined_raw_atomic_long_dec_unless_positive(atomic_long_t *v)
{
	return raw_atomic_long_dec_unless_positive(v);
}

noinline bool
outlined_atomic_long_dec_unless_positive(atomic_long_t *v)
{
	return atomic_long_dec_unless_positive(v);
}

noinline noinstr long
outlined_raw_atomic_long_dec_if_positive(atomic_long_t *v)
{
	return raw_atomic_long_dec_if_positive(v);
}

noinline long
outlined_atomic_long_dec_if_positive(atomic_long_t *v)
{
	return atomic_long_dec_if_positive(v);
}

#endif /* _LINUX_ATOMIC_OUTLINED_H */
// 649efc6c7a35046d3ac59433e6e2e60ddcba8115
