// SPDX-License-Identifier: GPL-2.0

// Generated by scripts/atomic/gen-atomic-stats.sh
// DO NOT MODIFY THIS FILE DIRECTLY

#ifndef _LINUX_ATOMIC_STATS_H
#define _LINUX_ATOMIC_STATS_H

#if defined(CONFIG_ATOMIC_STATS) && !defined(DISABLE_ATOMIC_STATS)
/*
 * This macro will use __do() on each atomic_*() operation in turn.
 * This can be used to generate enums and enum-to-string tables.
 */
#define __do_atomic_stats_ops(__do)	\
	__do(atomic_read) \
	__do(atomic_read_acquire) \
	__do(atomic_set) \
	__do(atomic_set_release) \
	__do(atomic_add) \
	__do(atomic_add_return) \
	__do(atomic_add_return_acquire) \
	__do(atomic_add_return_release) \
	__do(atomic_add_return_relaxed) \
	__do(atomic_fetch_add) \
	__do(atomic_fetch_add_acquire) \
	__do(atomic_fetch_add_release) \
	__do(atomic_fetch_add_relaxed) \
	__do(atomic_sub) \
	__do(atomic_sub_return) \
	__do(atomic_sub_return_acquire) \
	__do(atomic_sub_return_release) \
	__do(atomic_sub_return_relaxed) \
	__do(atomic_fetch_sub) \
	__do(atomic_fetch_sub_acquire) \
	__do(atomic_fetch_sub_release) \
	__do(atomic_fetch_sub_relaxed) \
	__do(atomic_inc) \
	__do(atomic_inc_return) \
	__do(atomic_inc_return_acquire) \
	__do(atomic_inc_return_release) \
	__do(atomic_inc_return_relaxed) \
	__do(atomic_fetch_inc) \
	__do(atomic_fetch_inc_acquire) \
	__do(atomic_fetch_inc_release) \
	__do(atomic_fetch_inc_relaxed) \
	__do(atomic_dec) \
	__do(atomic_dec_return) \
	__do(atomic_dec_return_acquire) \
	__do(atomic_dec_return_release) \
	__do(atomic_dec_return_relaxed) \
	__do(atomic_fetch_dec) \
	__do(atomic_fetch_dec_acquire) \
	__do(atomic_fetch_dec_release) \
	__do(atomic_fetch_dec_relaxed) \
	__do(atomic_and) \
	__do(atomic_fetch_and) \
	__do(atomic_fetch_and_acquire) \
	__do(atomic_fetch_and_release) \
	__do(atomic_fetch_and_relaxed) \
	__do(atomic_andnot) \
	__do(atomic_fetch_andnot) \
	__do(atomic_fetch_andnot_acquire) \
	__do(atomic_fetch_andnot_release) \
	__do(atomic_fetch_andnot_relaxed) \
	__do(atomic_or) \
	__do(atomic_fetch_or) \
	__do(atomic_fetch_or_acquire) \
	__do(atomic_fetch_or_release) \
	__do(atomic_fetch_or_relaxed) \
	__do(atomic_xor) \
	__do(atomic_fetch_xor) \
	__do(atomic_fetch_xor_acquire) \
	__do(atomic_fetch_xor_release) \
	__do(atomic_fetch_xor_relaxed) \
	__do(atomic_xchg) \
	__do(atomic_xchg_acquire) \
	__do(atomic_xchg_release) \
	__do(atomic_xchg_relaxed) \
	__do(atomic_cmpxchg) \
	__do(atomic_cmpxchg_acquire) \
	__do(atomic_cmpxchg_release) \
	__do(atomic_cmpxchg_relaxed) \
	__do(atomic_try_cmpxchg) \
	__do(atomic_try_cmpxchg_acquire) \
	__do(atomic_try_cmpxchg_release) \
	__do(atomic_try_cmpxchg_relaxed) \
	__do(atomic_sub_and_test) \
	__do(atomic_dec_and_test) \
	__do(atomic_inc_and_test) \
	__do(atomic_add_negative) \
	__do(atomic_add_negative_acquire) \
	__do(atomic_add_negative_release) \
	__do(atomic_add_negative_relaxed) \
	__do(atomic_fetch_add_unless) \
	__do(atomic_add_unless) \
	__do(atomic_inc_not_zero) \
	__do(atomic_inc_unless_negative) \
	__do(atomic_dec_unless_positive) \
	__do(atomic_dec_if_positive) \
	__do(atomic64_read) \
	__do(atomic64_read_acquire) \
	__do(atomic64_set) \
	__do(atomic64_set_release) \
	__do(atomic64_add) \
	__do(atomic64_add_return) \
	__do(atomic64_add_return_acquire) \
	__do(atomic64_add_return_release) \
	__do(atomic64_add_return_relaxed) \
	__do(atomic64_fetch_add) \
	__do(atomic64_fetch_add_acquire) \
	__do(atomic64_fetch_add_release) \
	__do(atomic64_fetch_add_relaxed) \
	__do(atomic64_sub) \
	__do(atomic64_sub_return) \
	__do(atomic64_sub_return_acquire) \
	__do(atomic64_sub_return_release) \
	__do(atomic64_sub_return_relaxed) \
	__do(atomic64_fetch_sub) \
	__do(atomic64_fetch_sub_acquire) \
	__do(atomic64_fetch_sub_release) \
	__do(atomic64_fetch_sub_relaxed) \
	__do(atomic64_inc) \
	__do(atomic64_inc_return) \
	__do(atomic64_inc_return_acquire) \
	__do(atomic64_inc_return_release) \
	__do(atomic64_inc_return_relaxed) \
	__do(atomic64_fetch_inc) \
	__do(atomic64_fetch_inc_acquire) \
	__do(atomic64_fetch_inc_release) \
	__do(atomic64_fetch_inc_relaxed) \
	__do(atomic64_dec) \
	__do(atomic64_dec_return) \
	__do(atomic64_dec_return_acquire) \
	__do(atomic64_dec_return_release) \
	__do(atomic64_dec_return_relaxed) \
	__do(atomic64_fetch_dec) \
	__do(atomic64_fetch_dec_acquire) \
	__do(atomic64_fetch_dec_release) \
	__do(atomic64_fetch_dec_relaxed) \
	__do(atomic64_and) \
	__do(atomic64_fetch_and) \
	__do(atomic64_fetch_and_acquire) \
	__do(atomic64_fetch_and_release) \
	__do(atomic64_fetch_and_relaxed) \
	__do(atomic64_andnot) \
	__do(atomic64_fetch_andnot) \
	__do(atomic64_fetch_andnot_acquire) \
	__do(atomic64_fetch_andnot_release) \
	__do(atomic64_fetch_andnot_relaxed) \
	__do(atomic64_or) \
	__do(atomic64_fetch_or) \
	__do(atomic64_fetch_or_acquire) \
	__do(atomic64_fetch_or_release) \
	__do(atomic64_fetch_or_relaxed) \
	__do(atomic64_xor) \
	__do(atomic64_fetch_xor) \
	__do(atomic64_fetch_xor_acquire) \
	__do(atomic64_fetch_xor_release) \
	__do(atomic64_fetch_xor_relaxed) \
	__do(atomic64_xchg) \
	__do(atomic64_xchg_acquire) \
	__do(atomic64_xchg_release) \
	__do(atomic64_xchg_relaxed) \
	__do(atomic64_cmpxchg) \
	__do(atomic64_cmpxchg_acquire) \
	__do(atomic64_cmpxchg_release) \
	__do(atomic64_cmpxchg_relaxed) \
	__do(atomic64_try_cmpxchg) \
	__do(atomic64_try_cmpxchg_acquire) \
	__do(atomic64_try_cmpxchg_release) \
	__do(atomic64_try_cmpxchg_relaxed) \
	__do(atomic64_sub_and_test) \
	__do(atomic64_dec_and_test) \
	__do(atomic64_inc_and_test) \
	__do(atomic64_add_negative) \
	__do(atomic64_add_negative_acquire) \
	__do(atomic64_add_negative_release) \
	__do(atomic64_add_negative_relaxed) \
	__do(atomic64_fetch_add_unless) \
	__do(atomic64_add_unless) \
	__do(atomic64_inc_not_zero) \
	__do(atomic64_inc_unless_negative) \
	__do(atomic64_dec_unless_positive) \
	__do(atomic64_dec_if_positive) \
	__do(atomic_long_read) \
	__do(atomic_long_read_acquire) \
	__do(atomic_long_set) \
	__do(atomic_long_set_release) \
	__do(atomic_long_add) \
	__do(atomic_long_add_return) \
	__do(atomic_long_add_return_acquire) \
	__do(atomic_long_add_return_release) \
	__do(atomic_long_add_return_relaxed) \
	__do(atomic_long_fetch_add) \
	__do(atomic_long_fetch_add_acquire) \
	__do(atomic_long_fetch_add_release) \
	__do(atomic_long_fetch_add_relaxed) \
	__do(atomic_long_sub) \
	__do(atomic_long_sub_return) \
	__do(atomic_long_sub_return_acquire) \
	__do(atomic_long_sub_return_release) \
	__do(atomic_long_sub_return_relaxed) \
	__do(atomic_long_fetch_sub) \
	__do(atomic_long_fetch_sub_acquire) \
	__do(atomic_long_fetch_sub_release) \
	__do(atomic_long_fetch_sub_relaxed) \
	__do(atomic_long_inc) \
	__do(atomic_long_inc_return) \
	__do(atomic_long_inc_return_acquire) \
	__do(atomic_long_inc_return_release) \
	__do(atomic_long_inc_return_relaxed) \
	__do(atomic_long_fetch_inc) \
	__do(atomic_long_fetch_inc_acquire) \
	__do(atomic_long_fetch_inc_release) \
	__do(atomic_long_fetch_inc_relaxed) \
	__do(atomic_long_dec) \
	__do(atomic_long_dec_return) \
	__do(atomic_long_dec_return_acquire) \
	__do(atomic_long_dec_return_release) \
	__do(atomic_long_dec_return_relaxed) \
	__do(atomic_long_fetch_dec) \
	__do(atomic_long_fetch_dec_acquire) \
	__do(atomic_long_fetch_dec_release) \
	__do(atomic_long_fetch_dec_relaxed) \
	__do(atomic_long_and) \
	__do(atomic_long_fetch_and) \
	__do(atomic_long_fetch_and_acquire) \
	__do(atomic_long_fetch_and_release) \
	__do(atomic_long_fetch_and_relaxed) \
	__do(atomic_long_andnot) \
	__do(atomic_long_fetch_andnot) \
	__do(atomic_long_fetch_andnot_acquire) \
	__do(atomic_long_fetch_andnot_release) \
	__do(atomic_long_fetch_andnot_relaxed) \
	__do(atomic_long_or) \
	__do(atomic_long_fetch_or) \
	__do(atomic_long_fetch_or_acquire) \
	__do(atomic_long_fetch_or_release) \
	__do(atomic_long_fetch_or_relaxed) \
	__do(atomic_long_xor) \
	__do(atomic_long_fetch_xor) \
	__do(atomic_long_fetch_xor_acquire) \
	__do(atomic_long_fetch_xor_release) \
	__do(atomic_long_fetch_xor_relaxed) \
	__do(atomic_long_xchg) \
	__do(atomic_long_xchg_acquire) \
	__do(atomic_long_xchg_release) \
	__do(atomic_long_xchg_relaxed) \
	__do(atomic_long_cmpxchg) \
	__do(atomic_long_cmpxchg_acquire) \
	__do(atomic_long_cmpxchg_release) \
	__do(atomic_long_cmpxchg_relaxed) \
	__do(atomic_long_try_cmpxchg) \
	__do(atomic_long_try_cmpxchg_acquire) \
	__do(atomic_long_try_cmpxchg_release) \
	__do(atomic_long_try_cmpxchg_relaxed) \
	__do(atomic_long_sub_and_test) \
	__do(atomic_long_dec_and_test) \
	__do(atomic_long_inc_and_test) \
	__do(atomic_long_add_negative) \
	__do(atomic_long_add_negative_acquire) \
	__do(atomic_long_add_negative_release) \
	__do(atomic_long_add_negative_relaxed) \
	__do(atomic_long_fetch_add_unless) \
	__do(atomic_long_add_unless) \
	__do(atomic_long_inc_not_zero) \
	__do(atomic_long_inc_unless_negative) \
	__do(atomic_long_dec_unless_positive) \
	__do(atomic_long_dec_if_positive) \
	/* consume trailing newline escape */

#define __do_atomic_stats_enum(x)	ATOMIC_STATS_##x,

enum atomic_stats_op {
	__do_atomic_stats_ops(__do_atomic_stats_enum)
	NR_ATOMIC_STATS_OPS
};

void __atomic_stats_inc(enum atomic_stats_op op);
#define atomic_stats_inc(op) \
	__atomic_stats_inc(ATOMIC_STATS_##op);

void __atomic_stats_bool_inc(enum atomic_stats_op op, bool ret);
#define atomic_stats_bool_inc(op, ret) \
	__atomic_stats_bool_inc(ATOMIC_STATS_##op, ret);

#else
#define atomic_stats_inc(op)
#define atomic_stats_bool_inc(op, ret)
#endif

#endif /* _LINUX_ATOMIC_STATS_H */
// 05c3f8d2e04d9aa28c1edfe3cefcabb9d5303bdf
